<a href="https://colab.research.google.com/github/Vixuz144/MN1/blob/main/Ejercicio_Lagrange.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [68]:
def inter_lag(X, Y, x):
  l = []
  for i in range(n):
    a = x-np.append(X[:i], X[i+1:])
    b = X[i]-np.append(X[:i], X[i+1:])
    l.append(np.prod(a/b))
  l = np.array(l)
  return np.dot(Y, l)

In [2]:
fa = lambda x: np.cos(x)
fb = lambda x: np.sqrt(x+1)
fc = lambda x: np.log(x+1)
fd = lambda x: np.tan(x)

In [67]:
X = np.array([0, 0.6, 0.9])
n = len(X)
x = 0.45

In [72]:
a = inter_lag(X, fa(X), x)
b = inter_lag(X, fb(X), x)
c = inter_lag(X, fc(X), x)
d = inter_lag(X, fd(X), x)
print(a, fa(x), a - fa(x))
print(b, fb(x), b - fb(x))
print(c, fc(x), c - fc(x))
print(d, fd(x), d - fd(x))

0.898100074705722 0.9004471023526769 -0.0023470276469549356
1.2034237282735152 1.2041594578792296 -0.0007357296057144413
0.36829061135835384 0.371563556432483 -0.0032729450741291743
0.454614354996819 0.4830550656165784 -0.02844071061975939


In [78]:
print(0.6+0.9, 0.6*0.9)
print(fa(X))
print(fb(X))
print(np.sqrt(1-X), np.sqrt(1-x))

1.5 0.54
[1.         0.82533561 0.62160997]
[1.         1.26491106 1.37840488]
[1.         0.63245553 0.31622777] 0.7416198487095663
