<a href="https://colab.research.google.com/github/Vixuz144/MN1/blob/main/Ejercicios_Neville.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [138]:
import numpy as np
import sympy as sp
import pandas as pd

In [139]:
x = sp.Symbol('x')

In [140]:
X = [1, 1.3, 1.6, 1.9, 2.2]
Y = [0.7651977, 0.6200860, 0.4554022, 0.2818186, 0.1103623]



In [141]:
def Neville(X, Y, x=x, dec=5):
  n = len(X)
  M = np.zeros((n,n+1))*x
  M[:,:2] = np.stack((X,Y),1)
  for i in range(1,n):
    for j in range(n-i):
      M[j,i+1] = ((x-X[j])*M[j+1,i] - (x-X[j+i])*M[j,i]) / (X[j+i]-X[j])
  try:
    M = np.round(M, dec)
    return M
  except:
    return M[0,-1]

print(Neville(X,Y,1.5))

[[1.      0.7652  0.52334 0.51247 0.51181 0.51182]
 [1.3     0.62009 0.5103  0.51129 0.51183 0.     ]
 [1.6     0.4554  0.51326 0.51374 0.      0.     ]
 [1.9     0.28182 0.51043 0.      0.      0.     ]
 [2.2     0.11036 0.      0.      0.      0.     ]]


In [142]:
3**-1

0.3333333333333333

In [143]:
X = [-2,-1,0,1,2]
Y = []
for i in X:
  Y.append(3**i)
print(Y)
print(Neville(X, Y, 0.5))

[0.1111111111111111, 0.3333333333333333, 1, 3, 9]
[[-2.       0.11111  0.66667  1.5      1.77778  1.70833]
 [-1.       0.33333  1.33333  1.83333  1.66667  0.     ]
 [ 0.       1.       2.       1.5      0.       0.     ]
 [ 1.       3.       0.       0.       0.       0.     ]
 [ 2.       9.       0.       0.       0.       0.     ]]


In [144]:
X = [0, 1, 2, 4, 5]
print(Neville(X,np.sqrt(X),3))

[[0.      0.      3.      1.24264 1.62132 1.69061]
 [1.      1.      1.82843 1.74755 1.7368  0.     ]
 [2.      1.41421 1.70711 1.72605 0.      0.     ]
 [4.      2.      1.76393 0.      0.      0.     ]
 [5.      2.23607 0.      0.      0.      0.     ]]


In [145]:
X = [0, 0.4, 0.7]
Y = [0, 2.8, 6.4]
print(Neville(X,Y,0.5))

[[0.      0.      3.5     3.85714]
 [0.4     2.8     4.      0.     ]
 [0.7     6.4     0.      0.     ]]
